Repository snobu/destreamer, pull requests merged in 2020-04, with the labels that each got.

#59 Fixes
  .gitignore
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  scripts/make_release.sh
  src/CommandLineParser.ts
  src/Errors.ts
  src/Events.ts
  src/Metadata.ts
  src/PuppeteerHelper.ts
  src/Types.ts
  src/Utils.ts
  src/destreamer.ts
  test/test.ts
Labels: enhancement

#63 Adding temporary bootstrapers until we move to single binary releases
  destreamer.cmd
  destreamer.ps1
  destreamer.sh
Labels: UX

#79 Reintroduce Node 8.x support
  .github/workflows/build.yaml
  README.md
  src/destreamer.ts
  tsconfig.json
Labels: enhancement

#84 Workaround for Cygwin/MSYS progress bar
  src/destreamer.ts
Labels: bug

#93 Add mid-download token refresh, fix headers length overflow bug
  .gitignore
  .vscode/launch.json
  README.md
  destreamer.cmd
  destreamer.ps1
  destreamer.sh
  package-lock.json
  package.json
  src/TokenCache.ts
  src/destreamer.ts
  test/test.ts
  tsconfig.json
Labels: enhancement
